[package]
name = "iron-restsvc"
version = "0.1.0"
authors = ["tomwallick <tom.wallick@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
time = "0.2.1"
iron = "0.6.1"
serde_json = "1.0.44"
